apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: alpine
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  labels:
    name: alpine
spec:
  # hostname: alpine-1
  subdomain: default-subdomain
  containers:
  - image: alpine:3.14
    command:
      - sleep
      - "3600"
    name: alpine
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: alpine2
#   labels:
#     name: alpine
# spec:
#   # hostname: alpine-2
#   subdomain: default-subdomain
#   containers:
#   - image: alpine:3.14
#     command:
#       - sleep
#       - "3600"
#     name: alpine
