apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: test
    image: redis
    volumeMounts:
    - name: foo
      mountPath: /etc/mysecret
      readOnly: true
    - name: db-user-pass
      mountPath: /etc/foo
      subPath: db-user-pass
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      defaultMode: 0655
      optional: false
  - name: db-user-pass
    secret:
      secretName: db-user-pass
      items:
      - key: username
        path: db-user-pass/username
      - key: password
        path: db-user-pass/password
